### ISSUE TITLE
Any implementation on other datasets?

### ISSUE THREAD

**Issue by zbliu98** [frigategnn/Frigate#3]
Hi,

Your work is really interesting. Have you ever tried other common traffic datasets? Like PEMS series? They are the ones with fewer nodes and edges. Hope to hear from you.

**Comment by frigategnn** [comment]
As of now there are no implementations on datasets other than the ones provided here. There is also no plan of implementing it in future, as of now. However, an extension to other datasets is straight-forward, though some parameter tuning might be required.
